public class Calcu {
    public static Decimal Addition(Decimal var1,Decimal var2){
        Decimal sum = 0;
        sum = var1+var2;
        return sum;
    }
    public static Decimal Substraction(Decimal var1,Decimal var2){
        Decimal sub = 0;
        sub = var1-var2;
        return sub;
    }
    public static Decimal Multiplication(Decimal var1,Decimal var2){
        Decimal mul = 0;
        mul = var1*var2;
        return mul;
    }
    public static Decimal Division(Decimal var1,Decimal var2){
        Decimal div = 0;
        div = var1/var2;
        return div;
    }
}