@isTest
public class CalcuTestClass {
    @isTest
    static void operationTestsAdd(){
        Calcu.Addition(23.99,99.09);            
    }
    @isTest
    static void operationTestsSub(){
        Calcu.Substraction(45.86,-45.98);
        
    }@isTest
    static void operationTestsMul(){
        Calcu.Multiplication(78,-99);
        
    }@isTest
    static void operationTestsDiv(){
        Calcu.Division(-24,-89);        
    } 
}